version: "3.9"
services:
  postgres:
    image: postgres:17
    container_name: hackathon-postgres
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon
      POSTGRES_DB: hotel_hackathon
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "5050:80"
    restart: always